[package]
name = "rust-learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
infer = "0.15.0"
diesel = { version = "2.1.0", features = ["postgres"] }
dotenvy = "0.15"
diesel_migrations = "2.1.0"

