-- Seed ALL permissions for SUPER_ADMIN platform role (idempotent)
-- This ensures platform has a complete baseline; other roles can be filled incrementally.
-- Source of truth for permission names: src/config/constants/permissions.rs

WITH perms(permission) AS (
    VALUES
        ('CREATE_ORGANIZATION'),
        ('MODIFY_ORGANIZATION'),
        ('DELETE_ORGANIZATION'),
        ('VIEW_ORGANIZATION'),
        ('REQUEST_JOIN_ORGANIZATION'),
        ('ACCEPT_ORGANIZATION_JOIN_REQUEST'),
        ('CREATE_COURSE'),
        ('MODIFY_COURSE'),
        ('DELETE_COURSE'),
        ('VIEW_COURSE'),
        ('JOIN_COURSE'),
        ('REQUEST_JOIN_COURSE'),
        ('APPROVE_COURSE_JOIN_REQUESTS'),
        ('MODIFY_USER'),
        ('DELETE_USER'),
        ('VIEW_USER'),
        ('INVITE_USER_TO_ORGANIZATION'),
        ('MODIFY_ROLE'),
        ('DELETE_ROLE'),
        ('ASSIGN_ROLES_TO_USER'),
        ('MODIFY_PERMISSION'),
        ('CREATE_CONTENT'),
        ('MODIFY_CONTENT'),
        ('DELETE_CONTENT'),
        ('VIEW_CONTENT'),
        ('CREATE_ASSESSMENT'),
        ('MODIFY_ASSESSMENT'),
        ('DELETE_ASSESSMENT'),
        ('GRADE_ASSESSMENT'),
        ('VIEW_ASSESSMENT'),
        ('POST_IN_DISCUSSION'),
        ('MODERATE_DISCUSSION'),
        ('SEND_NOTIFICATION'),
        ('VIEW_NOTIFICATION'),
        ('VIEW_REPORT'),
        ('GENERATE_REPORT'),
        ('CREATE_WALLET'),
        ('VIEW_WALLET'),
        ('MANAGE_WALLETS'),
        ('TRANSFER_MONEY'),
        ('DEPOSIT_MONEY'),
        ('WITHDRAW_MONEY'),
        ('VIEW_TRANSACTIONS'),
        ('CENTRALIZED_WALLET_TRANSFER'),
        ('MANAGE_PLATFORM_SETTINGS'),
        ('MANAGE_API_KEYS'),
        ('MANAGE_INTEGRATIONS'),
        ('VIEW_AUDIT_LOGS'),
        ('IMPERSONATE_USER'),
        ('MANAGE_BILLING'),
        ('EXPORT_DATA'),
        ('RUN_MAINTENANCE_TASKS'),
        ('MANAGE_ORG_MEMBERS'),
        ('MANAGE_ORG_SETTINGS'),
        ('MANAGE_ORG_BILLING'),
        ('MANAGE_ORG_WALLETS'),
        ('MANAGE_COURSE_ENROLLMENTS'),
        ('APPROVE_COURSE_CONTENT'),
        ('PUBLISH_CONTENT'),
        ('MANAGE_COURSE_SETTINGS'),
        ('CREATE_COURSE_TEMPLATES'),
        ('MANAGE_ASSESSMENT_TEMPLATES'),
        ('MANAGE_ROLE_PERMISSIONS'),
        ('VIEW_ROLE_ASSIGNMENTS'),
        ('ASSIGN_ROLES_TO_ORG_USERS'),
        ('INITIATE_EXTERNAL_TRANSFER'),
        ('APPROVE_CENTRALIZED_TRANSFER'),
        ('REFUND_TRANSACTION'),
        ('RECONCILE_WALLETS'),
        ('MANAGE_PAYMENT_METHODS'),
        ('VIEW_FINANCIAL_REPORTS'),
        ('VIEW_SENSITIVE_TRANSACTIONS'),
        ('EXPORT_TRANSACTIONS'),
        ('MANAGE_COMPLIANCE_FLAGS'),
        ('MANAGE_DISCUSSIONS'),
        ('SUSPEND_USER'),
        ('BAN_USER'),
        ('MANAGE_NOTIFICATION_TEMPLATES'),
        ('SEND_BULK_NOTIFICATION'),
        ('MANAGE_SMART_CONTRACTS'),
        ('MANAGE_MINIO_OBJECTS'),
        ('MANAGE_ETHEREUM_ACCOUNTS'),
        ('VIEW_ANALYTICS_DASHBOARD'),
        ('MANAGE_EXPORT_JOBS'),
        ('RUN_TESTS'),
        ('VIEW_TEST_RESULTS'),
        ('MANAGE_TEST_SUITES'),
        ('TAKE_TESTS')
), super_admin AS (
    SELECT id FROM platform_roles WHERE name = 'SUPER_ADMIN'
)
INSERT INTO role_permission_platform (platform_role_id, permission)
SELECT sa.id, p.permission
FROM perms p CROSS JOIN super_admin sa
WHERE NOT EXISTS (
    SELECT 1 FROM role_permission_platform rpp
    WHERE rpp.platform_role_id = sa.id
      AND rpp.permission = p.permission
);
