use actix_web::http::Method;

pub fn route_smoke_targets() -> Vec<(Method, &'static str)> {
    vec![
        (Method::GET, "/api/courses"),
        (Method::POST, "/api/courses"),
        (Method::GET, "/api/user"),
        (Method::GET, "/api/user/12"),
        (Method::POST, "/api/user/12/role"),
        (Method::GET, "/api/teacher-applications"),
        (Method::GET, "/api/teacher-applications/review"),
        (Method::GET, "/api/teacher-applications/me"),
        (Method::POST, "/api/teacher-applications"),
        (Method::PUT, "/api/teacher-applications/34/decision"),
        (Method::GET, "/api/kyc/me"),
        (Method::POST, "/api/kyc/me"),
        (Method::GET, "/api/kyc/review"),
        (Method::PUT, "/api/kyc/review/34"),
        (Method::GET, "/api/kyc/review/34/audit"),
        (Method::GET, "/api/courses/teaching"),
        (Method::GET, "/api/courses/teaching/12"),
        (Method::GET, "/api/courses/teaching/12/enrollments"),
        (Method::GET, "/api/courses/teaching/12/students"),
        (Method::GET, "/api/courses/12"),
        (Method::PUT, "/api/courses/12"),
        (Method::GET, "/api/courses/12/organizations"),
        (Method::PUT, "/api/courses/12/lifecycle"),
        (Method::DELETE, "/api/courses/12"),
        (Method::GET, "/api/reward-candidates/me/history"),
        (Method::GET, "/api/reward-candidates/review"),
        (Method::GET, "/api/courses/12/reward-candidates"),
        (Method::POST, "/api/courses/12/reward-candidates"),
        (
            Method::PUT,
            "/api/courses/12/reward-candidates/34/teacher-decision",
        ),
        (Method::PUT, "/api/reward-candidates/34/amount-decision"),
        (Method::GET, "/api/reward-candidates/34/audit"),
        (
            Method::POST,
            "/api/organizations/56/courses/12/reward-candidates",
        ),
        (Method::GET, "/api/reports/platform/summary"),
        (Method::GET, "/api/reports/platform/summary.csv"),
        (Method::GET, "/api/reports/platform/reward-dashboard"),
        (Method::GET, "/api/reports/platform/reward-dashboard.csv"),
        (Method::GET, "/api/reports/platform/fraud-dashboard"),
        (Method::GET, "/api/reports/platform/fraud-dashboard.csv"),
        (
            Method::GET,
            "/api/reports/platform/teacher-applications.csv",
        ),
        (Method::GET, "/api/reports/platform/reward-approvals.csv"),
        (Method::GET, "/api/reports/platform/token-payouts.csv"),
        (Method::GET, "/api/reports/platform/wallet-credits.csv"),
        (
            Method::GET,
            "/api/reports/platform/delegated-permissions.csv",
        ),
        (Method::GET, "/api/reports/platform/wallet-reconciliation"),
        (Method::GET, "/api/organizations"),
        (Method::POST, "/api/organizations"),
        (Method::GET, "/api/organizations/56"),
        (Method::PUT, "/api/organizations/56"),
        (Method::DELETE, "/api/organizations/56"),
        (Method::GET, "/api/organizations/56/courses"),
        (Method::GET, "/api/organizations/56/dashboard"),
        (Method::GET, "/api/organizations/56/members"),
        (Method::POST, "/api/organizations/56/members"),
        (Method::GET, "/api/organizations/56/members/78/audit"),
        (Method::DELETE, "/api/organizations/56/users/78"),
        (Method::POST, "/api/organizations/56/users/78/roles"),
        (Method::GET, "/api/organizations/56/teacher-applications"),
        (Method::POST, "/api/organizations/56/teacher-applications"),
        (Method::GET, "/api/reports/organizations/56/summary"),
        (Method::GET, "/api/reports/organizations/56/summary.csv"),
        (
            Method::GET,
            "/api/reports/organizations/56/reward-dashboard",
        ),
        (
            Method::GET,
            "/api/reports/organizations/56/reward-dashboard.csv",
        ),
        (Method::GET, "/api/reward-fraud-blocks"),
        (Method::POST, "/api/reward-fraud-blocks"),
        (Method::PUT, "/api/reward-fraud-blocks/78/revoke"),
        (Method::GET, "/api/reward-fraud-blocks/78/audit"),
        (Method::GET, "/api/delegated-permissions"),
        (Method::POST, "/api/delegated-permissions"),
        (Method::PUT, "/api/delegated-permissions/90/revoke"),
    ]
}
