include!("authentication_flow/imports.rs");
include!(
    "authentication_flow/login_requires_email_verification_and_returns_jwt_after_verification.rs"
);
include!(
    "authentication_flow/verify_email_marks_user_verified_and_reports_already_verified_replay.rs"
);
include!("authentication_flow/verify_email_reports_expired_and_invalid_tokens.rs");
include!("authentication_flow/register_rejects_duplicate_email_without_panicking.rs");
include!("authentication_flow/password_reset_request_and_completion.rs");
