include!("course_discovery/01_imports.rs");
include!("course_discovery/02_create_organization.rs");
include!("course_discovery/03_create_course_reward_policy.rs");
include!("course_discovery/04_course_search_treats_like_wildcards_as_literal_text.rs");
include!(
    "course_discovery/05_organization_course_list_uses_org_scope_and_returns_operator_summaries.rs"
);
include!(
    "course_discovery/06_learner_catalog_returns_published_course_summaries_and_pending_state.rs"
);
include!(
    "course_discovery/07_learner_catalog_includes_own_draft_but_hides_unscoped_draft_detail.rs"
);
include!("course_discovery/08_learner_learning_endpoint_returns_content_states_and_denies_unscoped_content.rs");
