include!("delegated_permissions/imports.rs");
include!("delegated_permissions/delegation_helper.rs");
include!("delegated_permissions/submission_helper.rs");
include!("delegated_permissions/force_assign_course_role.rs");
include!(
    "delegated_permissions/delegated_course_permission_submits_candidate_without_course_role.rs"
);
include!(
    "delegated_permissions/delegated_permission_grant_requires_platform_delegate_permission.rs"
);
include!("delegated_permissions/delegated_platform_amount_reviewer_can_set_amount_after_teacher_approval.rs");
include!("delegated_permissions/revoked_delegation_no_longer_authorizes_permission.rs");
