mod course_dto;
mod course_nested_dto;
mod courses;
mod dashboard;
mod dashboard_dto;
mod dashboard_summary_conversions;
mod dashboard_summary_dto;
mod dto;
mod handlers;
mod member_audit;
mod member_audit_dto;
mod member_dto;
mod member_invites;
mod member_list;
mod member_removal;
mod member_roles;
mod routes;
mod teacher_application_dto;
mod teacher_application_nested_dto;
mod teacher_applications;

pub use routes::{configure_routes, organization_scope};
