pub fn organization_scope() -> actix_web::Scope {
    web::scope("/organizations")
        .service(crate::http::rewards::organization_scope_reward_candidate_submission_resource())
        .service(
            web::resource("")
                .route(web::get().to(list_organizations).wrap(
                    PlatformPermissionMiddleware::require(
                        Permissions::VIEW_ORGANIZATION.to_string(),
                    ),
                ))
                .route(web::post().to(create_organization).wrap(
                    PlatformPermissionMiddleware::require(
                        Permissions::CREATE_ORGANIZATION.to_string(),
                    ),
                )),
        )
        .service(web::resource("/{id}/courses").route(web::get().to(get_organization_courses)))
        .service(
            web::resource("/{id}/members")
                .route(web::get().to(get_organization_members))
                .route(web::post().to(add_member_by_email_route).wrap(
                    OrganizationPermissionMiddleware::require(
                        "INVITE_USER_TO_ORGANIZATION".to_string(),
                        ParamType::Path,
                        "id".to_string(),
                    ),
                )),
        )
        .service(web::resource("/{id}/dashboard").route(web::get().to(get_organization_dashboard)))
        .service(
            web::resource("/{id}/members/{user_id}/audit").route(
                web::get().to(get_member_audit_route).wrap(
                    OrganizationPermissionMiddleware::require(
                        Permissions::VIEW_ORGANIZATION.to_string(),
                        ParamType::Path,
                        "id".to_string(),
                    ),
                ),
            ),
        )
        .service(
            web::resource("/{id}")
                .route(
                    web::get()
                        .to(get_organization)
                        .wrap(PlatformPermissionMiddleware::require(
                            Permissions::VIEW_ORGANIZATION.to_string(),
                        )),
                )
                .route(web::put().to(update_organization).wrap(
                    OrganizationPermissionMiddleware::require(
                        Permissions::MANAGE_ORG_SETTINGS.to_string(),
                        ParamType::Path,
                        "id".to_string(),
                    ),
                ))
                .route(web::delete().to(delete_organization).wrap(
                    OrganizationPermissionMiddleware::require(
                        Permissions::MANAGE_ORG_SETTINGS.to_string(),
                        ParamType::Path,
                        "id".to_string(),
                    ),
                )),
        )
        .service(
            web::resource("/{id}/users/{user_id}/roles").route(web::post().to(assign_role).wrap(
                OrganizationPermissionMiddleware::require(
                    Permissions::ASSIGN_ROLES_TO_ORG_USERS.to_string(),
                    ParamType::Path,
                    "id".to_string(),
                ),
            )),
        )
        .service(web::resource("/{id}/users/{user_id}").route(
            web::delete().to(remove_organization_member_route).wrap(
                OrganizationPermissionMiddleware::require(
                    Permissions::MANAGE_ORG_MEMBERS.to_string(),
                    ParamType::Path,
                    "id".to_string(),
                ),
            ),
        ))
        .service(
            web::resource("/{id}/teacher-applications")
                .route(web::get().to(get_organization_teacher_applications))
                .route(
                    web::post()
                        .to(crate::http::teacher_applications::nominate_application)
                        .wrap(OrganizationPermissionMiddleware::require(
                            Permissions::NOMINATE_TEACHER_FOR_PLATFORM_REVIEW.to_string(),
                            ParamType::Path,
                            "id".to_string(),
                        )),
                ),
        )
}
