pub fn reports_scope() -> actix_web::Scope {
    web::scope("/reports")
        .service(crate::http::reporting::platform_summary_resource())
        .service(crate::http::reporting::platform_summary_csv_resource())
        .service(web::resource("/platform/reward-dashboard").route(
            web::get().to(get_platform_reward_dashboard).wrap(
                PlatformPermissionMiddleware::require(Permissions::VIEW_REWARD_AUDIT.to_string()),
            ),
        ))
        .service(web::resource("/platform/reward-dashboard.csv").route(
            web::get().to(export_platform_reward_dashboard).wrap(
                PlatformPermissionMiddleware::require(Permissions::EXPORT_DATA.to_string()),
            ),
        ))
        .service(crate::http::reporting::platform_fraud_dashboard_resource())
        .service(crate::http::reporting::platform_fraud_dashboard_csv_resource())
        .service(web::resource("/platform/teacher-applications.csv").route(
            web::get().to(export_platform_teacher_applications).wrap(
                PlatformPermissionMiddleware::require(Permissions::EXPORT_DATA.to_string()),
            ),
        ))
        .service(web::resource("/platform/reward-approvals.csv").route(
            web::get().to(export_platform_reward_approvals).wrap(
                PlatformPermissionMiddleware::require(Permissions::EXPORT_DATA.to_string()),
            ),
        ))
        .service(web::resource("/platform/token-payouts.csv").route(
            web::get().to(export_platform_token_payouts).wrap(
                PlatformPermissionMiddleware::require(Permissions::EXPORT_DATA.to_string()),
            ),
        ))
        .service(web::resource("/platform/wallet-credits.csv").route(
            web::get().to(export_platform_wallet_credits).wrap(
                PlatformPermissionMiddleware::require(Permissions::EXPORT_DATA.to_string()),
            ),
        ))
        .service(web::resource("/platform/delegated-permissions.csv").route(
            web::get().to(export_platform_delegated_permissions).wrap(
                PlatformPermissionMiddleware::require(Permissions::EXPORT_DATA.to_string()),
            ),
        ))
        .service(web::resource("/platform/wallet-reconciliation").route(
            web::get().to(get_platform_wallet_reconciliation).wrap(
                PlatformPermissionMiddleware::require(Permissions::MANAGE_WALLETS.to_string()),
            ),
        ))
        .service(crate::http::reporting::organization_summary_resource())
        .service(crate::http::reporting::organization_summary_csv_resource())
        .service(web::resource("/organizations/{id}/reward-dashboard").route(
            web::get().to(get_organization_reward_dashboard).wrap(
                OrganizationPermissionMiddleware::require(
                    Permissions::VIEW_ORG_REWARD_REPORTS.to_string(),
                    ParamType::Path,
                    "id".to_string(),
                ),
            ),
        ))
        .service(
            web::resource("/organizations/{id}/reward-dashboard.csv").route(
                web::get().to(export_organization_reward_dashboard).wrap(
                    OrganizationPermissionMiddleware::require(
                        Permissions::VIEW_ORG_REWARD_REPORTS.to_string(),
                        ParamType::Path,
                        "id".to_string(),
                    ),
                ),
            ),
        )
}
