mod catalog_visibility;
pub mod status;
pub mod terms;

pub use catalog_visibility::is_generated_course_title;
pub use status::{
    CourseLifecycleStatus, CourseLifecycleStatusParseError, COURSE_STATUS_APPROVED,
    COURSE_STATUS_ARCHIVED, COURSE_STATUS_DRAFT, COURSE_STATUS_NEEDS_CHANGES,
    COURSE_STATUS_PUBLISHED, COURSE_STATUS_SUBMITTED, COURSE_STATUS_SUSPENDED,
};
pub use terms::{
    CourseCompletionTermsAuditEventType, CourseCompletionTermsParseError,
    CourseCompletionTermsStatus, COURSE_TERMS_EVENT_ACCEPTED, COURSE_TERMS_EVENT_ACTIVATED,
    COURSE_TERMS_EVENT_COUNTERED, COURSE_TERMS_EVENT_PROPOSED, COURSE_TERMS_EVENT_REJECTED,
    COURSE_TERMS_EVENT_SUPERSEDED, COURSE_TERMS_EVENT_WITHDRAWN, COURSE_TERMS_STATUS_ACCEPTED,
    COURSE_TERMS_STATUS_ACTIVE, COURSE_TERMS_STATUS_COUNTERED, COURSE_TERMS_STATUS_REJECTED,
    COURSE_TERMS_STATUS_SUBMITTED, COURSE_TERMS_STATUS_SUPERSEDED, COURSE_TERMS_STATUS_WITHDRAWN,
};

#[cfg(test)]
mod terms_tests;
