"use client";
export const DEFAULT_PERMISSION_KEYS = [
  "SUBMIT_TEACHER_APPLICATION",
  "REVIEW_TEACHER_APPLICATIONS",
  "APPROVE_TEACHER_APPLICATION",
  "REJECT_TEACHER_APPLICATION",
  "SUBMIT_COURSE_REWARD_EVENT",
  "VIEW_COURSE_REWARD_STATUS",
  "APPROVE_STUDENT_REWARD_CANDIDATE",
  "APPROVE_REWARD_AMOUNT",
  "VIEW_REPORT",
  "GENERATE_REPORT",
  "VIEW_ORG_REWARD_REPORTS",
  "VIEW_REWARD_AUDIT",
  "MANAGE_REWARD_FRAUD_BLOCKS",
  "DELEGATE_REWARD_APPROVAL",
  "EXPORT_DATA",
];
