"use client";
export const PROTECTED_ACTIONS = {
  submitTeacherApplication: "Submit teacher application",
  teacherApplicationQueue: "Teacher application queue",
  teacherApplicationDecision: "Teacher application decision",
  submitRewardCandidate: "Submit reward candidate",
  courseRewardCandidates: "Course reward candidates",
  courseRewardDecision: "Course reward decision",
  rewardAmountDecision: "Reward amount decision",
  studentRewardHistory: "Student reward history",
  organizationSummary: "Organization summary",
  organizationSummaryCsv: "Organization summary CSV",
  organizationRewardReport: "Organization reward report",
  organizationRewardCsv: "Organization reward CSV",
  platformSummary: "Platform summary",
  platformRewardDashboard: "Platform reward dashboard",
  platformFraudDashboard: "Platform fraud dashboard",
  createRewardFraudBlock: "Create reward fraud block",
  rewardFraudBlocks: "Reward fraud blocks",
  rewardFraudAudit: "Reward fraud audit",
  revokeRewardFraudBlock: "Revoke reward fraud block",
  grantDelegatedPermission: "Grant delegated permission",
  delegatedPermissions: "Delegated permissions",
  revokeDelegatedPermission: "Revoke delegated permission",
} as const;
