-- Roll back organization-level permission seeds for the covered roles

DELETE FROM role_permission_organization rpo
USING organization_roles r
WHERE rpo.organization_id IS NULL
  AND rpo.organization_role_id = r.id
  AND r.name IN ('SUPER_ADMIN','ADMIN','MODERATOR','TEACHER','STUDENT')
  AND rpo.permission IN (
    -- SUPER_ADMIN set
    'MANAGE_ORG_MEMBERS',
    'MANAGE_ORG_SETTINGS',
    'MANAGE_ORG_BILLING',
    'MANAGE_ORG_WALLETS',
    'INVITE_USER_TO_ORGANIZATION',
    'VIEW_USER',
    'VIEW_ORGANIZATION',
    'VIEW_REPORT',
    'GENERATE_REPORT',
    'MANAGE_NOTIFICATION_TEMPLATES',
    'SEND_BULK_NOTIFICATION',
    'SEND_NOTIFICATION',
    'VIEW_NOTIFICATION',
    'MANAGE_DISCUSSIONS',
    'MODERATE_DISCUSSION',
    'POST_IN_DISCUSSION',

    -- ADMIN subset
    'MANAGE_ORG_MEMBERS',
    'MANAGE_ORG_SETTINGS',
    'MANAGE_ORG_BILLING',
    'MANAGE_ORG_WALLETS',
    'INVITE_USER_TO_ORGANIZATION',
    'VIEW_USER',
    'VIEW_ORGANIZATION',
    'VIEW_REPORT',
    'GENERATE_REPORT',
    'SEND_NOTIFICATION',
    'VIEW_NOTIFICATION',
    'MANAGE_DISCUSSIONS',
    'MODERATE_DISCUSSION',
    'POST_IN_DISCUSSION',

    -- MODERATOR
    'MANAGE_DISCUSSIONS',
    'MODERATE_DISCUSSION',
    'POST_IN_DISCUSSION',
    'VIEW_NOTIFICATION',
    'SEND_NOTIFICATION',
    'VIEW_USER',

    -- TEACHER
    'POST_IN_DISCUSSION',
    'SEND_NOTIFICATION',
    'VIEW_NOTIFICATION',
    'VIEW_REPORT',
    'GENERATE_REPORT',

    -- STUDENT
    'VIEW_NOTIFICATION',
    'POST_IN_DISCUSSION',
    'VIEW_ORGANIZATION'
  );
