use actix_web::web;

use crate::bootstrap::app_state::AppState;

pub fn configure_app_data(cfg: &mut web::ServiceConfig, app_state: &AppState) {
    cfg.app_data(web::Data::new(app_state.pool.clone()))
        .app_data(web::Data::new(app_state.s3.clone()))
        .app_data(web::Data::new(app_state.notifications.clone()))
        .app_data(web::Data::new(app_state.role_catalog_use_case.clone()))
        .app_data(web::Data::new(app_state.current_session_use_case.clone()))
        .app_data(web::Data::new(app_state.course_deletion_use_case.clone()))
        .app_data(web::Data::new(
            app_state.course_organizations_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.notification_inbox_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.notification_preferences_use_case.clone(),
        ))
        .app_data(web::Data::new(app_state.chapter_use_cases.clone()))
        .app_data(web::Data::new(app_state.content_item_use_cases.clone()))
        .app_data(web::Data::new(
            app_state.content_upload_url_use_case.clone(),
        ))
        .app_data(web::Data::new(app_state.content_media_url_use_case.clone()))
        .app_data(web::Data::new(
            app_state.content_processing_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.reward_fraud_block_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.reward_candidate_audit_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.reward_amount_decision_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.reward_candidate_submission_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.course_reward_candidates_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.platform_reward_candidates_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.teacher_reward_candidate_decision_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.student_reward_history_use_case.clone(),
        ))
        .app_data(web::Data::new(app_state.reward_policy_use_case.clone()))
        .app_data(web::Data::new(app_state.wallet_audit_use_case.clone()))
        .app_data(web::Data::new(
            app_state.wallet_deposit_intent_use_case.clone(),
        ))
        .app_data(web::Data::new(app_state.wallet_link_use_case.clone()))
        .app_data(web::Data::new(app_state.wallet_read_use_case.clone()))
        .app_data(web::Data::new(app_state.wallet_retirement_use_case.clone()))
        .app_data(web::Data::new(app_state.wallet_token_tax_use_case.clone()))
        .app_data(web::Data::new(
            app_state.organization_reward_dashboard_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.organization_summary_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.platform_csv_exports_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.platform_fraud_dashboard_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.platform_reward_dashboard_use_case.clone(),
        ))
        .app_data(web::Data::new(app_state.platform_summary_use_case.clone()))
        .app_data(web::Data::new(
            app_state.platform_wallet_reconciliation_use_case.clone(),
        ))
        .app_data(web::Data::new(app_state.readiness_use_case.clone()));
}
