use actix_web::web;

use crate::bootstrap::app_state::AppState;

pub fn configure_app_data(cfg: &mut web::ServiceConfig, app_state: &AppState) {
    cfg.app_data(web::Data::new(app_state.pool.clone()))
        .app_data(web::Data::new(app_state.s3.clone()))
        .app_data(web::Data::new(app_state.notifications.clone()))
        .app_data(web::Data::new(app_state.role_catalog_use_case.clone()))
        .app_data(web::Data::new(app_state.current_session_use_case.clone()))
        .app_data(web::Data::new(app_state.kyc_use_cases.audit.clone()))
        .app_data(web::Data::new(app_state.kyc_use_cases.review.clone()))
        .app_data(web::Data::new(app_state.kyc_use_cases.status.clone()))
        .app_data(web::Data::new(app_state.kyc_use_cases.submission.clone()))
        .app_data(web::Data::new(app_state.course_creation_use_case.clone()))
        .app_data(web::Data::new(app_state.course_deletion_use_case.clone()))
        .app_data(web::Data::new(app_state.course_discovery_use_case.clone()))
        .app_data(web::Data::new(app_state.course_read_use_case.clone()))
        .app_data(web::Data::new(
            app_state.learner_course_catalog_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.learner_course_detail_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.learner_course_learning_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.teacher_course_dashboard_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.teacher_course_workspace_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.teacher_course_students_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state
                .teacher_course_enrollment_workspace_use_case
                .clone(),
        ))
        .app_data(web::Data::new(
            app_state.course_organizations_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.course_role_assignment_use_case.clone(),
        ))
        .app_data(web::Data::new(app_state.course_enrollment_use_case.clone()))
        .app_data(web::Data::new(app_state.course_update_use_case.clone()))
        .app_data(web::Data::new(app_state.course_lifecycle_use_case.clone()))
        .app_data(web::Data::new(app_state.learner_progress_use_case.clone()))
        .app_data(web::Data::new(
            app_state.course_assessments_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.assessment_attempts_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.assessment_submission_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.notification_inbox_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.notification_preferences_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.organization_use_cases.course_list.clone(),
        ))
        .app_data(web::Data::new(
            app_state.organization_use_cases.dashboard.clone(),
        ))
        .app_data(web::Data::new(
            app_state.organization_use_cases.management.clone(),
        ))
        .app_data(web::Data::new(
            app_state.organization_use_cases.member_audit.clone(),
        ))
        .app_data(web::Data::new(
            app_state.organization_use_cases.member_invite.clone(),
        ))
        .app_data(web::Data::new(
            app_state.organization_use_cases.member_list.clone(),
        ))
        .app_data(web::Data::new(
            app_state.organization_use_cases.member_removal.clone(),
        ))
        .app_data(web::Data::new(
            app_state
                .organization_use_cases
                .member_role_assignment
                .clone(),
        ))
        .app_data(web::Data::new(
            app_state
                .organization_use_cases
                .teacher_applications
                .clone(),
        ))
        .app_data(web::Data::new(app_state.chapter_use_cases.clone()))
        .app_data(web::Data::new(app_state.content_item_use_cases.clone()))
        .app_data(web::Data::new(
            app_state.content_upload_url_use_case.clone(),
        ))
        .app_data(web::Data::new(app_state.content_media_url_use_case.clone()))
        .app_data(web::Data::new(
            app_state.content_processing_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.reward_fraud_block_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.reward_candidate_audit_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.reward_amount_decision_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.reward_candidate_submission_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.course_reward_candidates_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.platform_reward_candidates_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.teacher_reward_candidate_decision_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.student_reward_history_use_case.clone(),
        ))
        .app_data(web::Data::new(app_state.reward_policy_use_case.clone()))
        .app_data(web::Data::new(app_state.wallet_audit_use_case.clone()))
        .app_data(web::Data::new(
            app_state.wallet_deposit_intent_use_case.clone(),
        ))
        .app_data(web::Data::new(app_state.wallet_link_use_case.clone()))
        .app_data(web::Data::new(app_state.wallet_read_use_case.clone()))
        .app_data(web::Data::new(app_state.wallet_retirement_use_case.clone()))
        .app_data(web::Data::new(app_state.wallet_token_tax_use_case.clone()))
        .app_data(web::Data::new(
            app_state.organization_reward_dashboard_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.organization_summary_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.platform_csv_exports_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.platform_fraud_dashboard_use_case.clone(),
        ))
        .app_data(web::Data::new(
            app_state.platform_reward_dashboard_use_case.clone(),
        ))
        .app_data(web::Data::new(app_state.platform_summary_use_case.clone()))
        .app_data(web::Data::new(
            app_state.platform_wallet_reconciliation_use_case.clone(),
        ))
        .app_data(web::Data::new(app_state.readiness_use_case.clone()));
}
