apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: secrets.patch.yaml
  - path: disable-ingress.patch.yaml
  - path: rustfs-local.patch.yaml
